package vistas.main;

import controlador.Controlador;
import javax.swing.JFrame;
import javax.swing.JLabel;
import utilidades.CambiaPanel;
import vistas.modulos.Dashboard;
import vistas.modulos.VistaUsuario;
import vistas.modulos.VistaEmpleado;

public class Menu extends javax.swing.JFrame {

    VistaUsuario vistaUsuario;
    int clicked = 1;
    
    
   VistaEmpleado vistaEmpleado;
 
   
   
    public Menu() {
        this.clicked = 7;
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        efectoPressed(btnDashboard);
    }
    
    public void setControlador(Controlador control){
        this.btnUsuarios.addMouseListener(control);
        this.btnDashboard.addMouseListener(control);
        this.btnEmpleados.addMouseListener(control);
    }
    
    public void iniciar(){
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPopupMenu1 = new javax.swing.JPopupMenu();
        aside = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JLabel();
        btnProductos = new javax.swing.JLabel();
        btnProveedores = new javax.swing.JLabel();
        btnFacturas = new javax.swing.JLabel();
        btnSucursales = new javax.swing.JLabel();
        btnEmpleados = new javax.swing.JLabel();
        btnPlanilla = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        aside.setBackground(new java.awt.Color(42, 53, 66));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 2);
        flowLayout1.setAlignOnBaseline(true);
        aside.setLayout(flowLayout1);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/more_info_35px.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(jLabel9, gridBagConstraints);

        btnDashboard.setBackground(new java.awt.Color(42, 53, 66));
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home_20px.png"))); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.setOpaque(true);
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashboardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDashboardMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.ipady = 22;
        jPanel2.add(btnDashboard, gridBagConstraints);

        btnProductos.setBackground(new java.awt.Color(42, 53, 66));
        btnProductos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empty_box_20px.png"))); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));
        btnProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProductos.setOpaque(true);
        btnProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProductosMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 109;
        gridBagConstraints.ipady = 22;
        jPanel2.add(btnProductos, gridBagConstraints);

        btnProveedores.setBackground(new java.awt.Color(42, 53, 66));
        btnProveedores.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnProveedores.setForeground(new java.awt.Color(255, 255, 255));
        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/truck_20px.png"))); // NOI18N
        btnProveedores.setText("Proveedores");
        btnProveedores.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));
        btnProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProveedores.setOpaque(true);
        btnProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProveedoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProveedoresMouseEntered(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(btnProveedores, gridBagConstraints);

        btnFacturas.setBackground(new java.awt.Color(42, 53, 66));
        btnFacturas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnFacturas.setForeground(new java.awt.Color(255, 255, 255));
        btnFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/purchase_order_20px.png"))); // NOI18N
        btnFacturas.setText("Facturas");
        btnFacturas.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));
        btnFacturas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFacturas.setOpaque(true);
        btnFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFacturasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFacturasMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(btnFacturas, gridBagConstraints);

        btnSucursales.setBackground(new java.awt.Color(42, 53, 66));
        btnSucursales.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnSucursales.setForeground(new java.awt.Color(255, 255, 255));
        btnSucursales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/business_building_20px.png"))); // NOI18N
        btnSucursales.setText("Sucursales");
        btnSucursales.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));
        btnSucursales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSucursales.setOpaque(true);
        btnSucursales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSucursalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSucursalesMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(btnSucursales, gridBagConstraints);

        btnEmpleados.setBackground(new java.awt.Color(42, 53, 66));
        btnEmpleados.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/suitcase_20px.png"))); // NOI18N
        btnEmpleados.setText("Empleados");
        btnEmpleados.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));
        btnEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpleados.setOpaque(true);
        btnEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmpleadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmpleadosMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(btnEmpleados, gridBagConstraints);

        btnPlanilla.setBackground(new java.awt.Color(42, 53, 66));
        btnPlanilla.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnPlanilla.setForeground(new java.awt.Color(255, 255, 255));
        btnPlanilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/page_20px.png"))); // NOI18N
        btnPlanilla.setText("Planilla de Empleados");
        btnPlanilla.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));
        btnPlanilla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlanilla.setOpaque(true);
        btnPlanilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPlanillaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPlanillaMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(btnPlanilla, gridBagConstraints);

        btnUsuarios.setBackground(new java.awt.Color(42, 53, 66));
        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_group_20px.png"))); // NOI18N
        btnUsuarios.setText("Control de Usuarios");
        btnUsuarios.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0)));
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.setOpaque(true);
        btnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUsuariosMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(btnUsuarios, gridBagConstraints);
        btnUsuarios.getAccessibleContext().setAccessibleName("VistaUsuarios");

        jLabel13.setBackground(new java.awt.Color(37, 46, 57));
        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("MENÚ");
        jLabel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jLabel13.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 202;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        jPanel2.add(jLabel13, gridBagConstraints);

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("JOSUE AGUILAR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        aside.add(jPanel2);

        getContentPane().add(aside, java.awt.BorderLayout.LINE_START);

        header.setBackground(new java.awt.Color(0, 166, 90));
        header.setLayout(new java.awt.GridBagLayout());

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Sistema de Ventas y Planillas | Panel de Control");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 10.0;
        header.add(jLabel10, gridBagConstraints);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/squared_menu_22px.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = 14;
        header.add(jLabel12, gridBagConstraints);

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(236, 240, 245));
        body.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        body.setForeground(new java.awt.Color(204, 204, 204));
        body.setLayout(new javax.swing.BoxLayout(body, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(body, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseClicked

    }//GEN-LAST:event_btnUsuariosMouseClicked

    private void btnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseClicked
 
    }//GEN-LAST:event_btnDashboardMouseClicked

    private void btnProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductosMouseEntered
       efectoEntered(btnProductos);
    }//GEN-LAST:event_btnProductosMouseEntered

    private void btnProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductosMouseExited
        efectoExited(btnProductos, 2);
    }//GEN-LAST:event_btnProductosMouseExited

    private void btnProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedoresMouseClicked
        efectoEntered(btnProveedores);
    }//GEN-LAST:event_btnProveedoresMouseClicked

    private void btnProveedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedoresMouseEntered
        efectoExited(btnProveedores, 3);
    }//GEN-LAST:event_btnProveedoresMouseEntered

    private void btnFacturasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacturasMouseEntered
        efectoEntered(btnFacturas);
    }//GEN-LAST:event_btnFacturasMouseEntered

    private void btnFacturasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacturasMouseExited
        efectoExited(btnFacturas, 4);
    }//GEN-LAST:event_btnFacturasMouseExited

    private void btnSucursalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSucursalesMouseEntered
        efectoEntered(btnSucursales);
    }//GEN-LAST:event_btnSucursalesMouseEntered

    private void btnSucursalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSucursalesMouseExited
        efectoExited(btnSucursales, 5);
    }//GEN-LAST:event_btnSucursalesMouseExited

    private void btnEmpleadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadosMouseEntered
        efectoEntered(btnEmpleados);
    }//GEN-LAST:event_btnEmpleadosMouseEntered

    private void btnEmpleadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadosMouseExited
        efectoExited(btnEmpleados, 6);
    }//GEN-LAST:event_btnEmpleadosMouseExited

    private void btnPlanillaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlanillaMouseEntered
        efectoEntered(btnPlanilla);
    }//GEN-LAST:event_btnPlanillaMouseEntered

    private void btnPlanillaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlanillaMouseExited
        efectoExited(btnPlanilla, 7);
    }//GEN-LAST:event_btnPlanillaMouseExited

    private void btnUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseEntered
        efectoEntered(btnUsuarios);
    }//GEN-LAST:event_btnUsuariosMouseEntered

    private void btnUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseExited
        efectoExited(btnUsuarios, 8);
    }//GEN-LAST:event_btnUsuariosMouseExited

    private void btnDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseEntered
        efectoEntered(btnDashboard);
    }//GEN-LAST:event_btnDashboardMouseEntered

    private void btnDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseExited
        efectoExited(btnDashboard, 1);
    }//GEN-LAST:event_btnDashboardMouseExited

    private void btnDashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMousePressed
        efectoReset(clicked);
        clicked = 1;
        efectoPressed(btnDashboard);
    }//GEN-LAST:event_btnDashboardMousePressed

    private void btnUsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMousePressed
        efectoReset(clicked);
        clicked = 8;
        efectoPressed(btnUsuarios);
    }//GEN-LAST:event_btnUsuariosMousePressed

    public void efectoEntered(JLabel label){
         label.setBackground(new java.awt.Color(37, 46, 57));
    }
    
    public void efectoExited(JLabel label, int n){
        if(clicked != n){
            label.setBackground(new java.awt.Color(42, 53, 66));
        }
    }
    
    public void efectoPressed(JLabel label){
        label.setBackground(new java.awt.Color(37, 46, 57));
        label.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(6, 156, 88)), javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0)));
    }
    
    public void efectoReset(int n){
        if(n == 1){
            btnDashboard.setBackground(new java.awt.Color(42, 53, 66));
            btnDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));
        }else if(n == 2 ){
            btnProductos.setBackground(new java.awt.Color(42, 53, 66));
            btnProductos.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));
        }else if(n == 3 ){
            btnProveedores.setBackground(new java.awt.Color(42, 53, 66));
            btnProveedores.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));
        }else if(n == 4 ){
            btnFacturas.setBackground(new java.awt.Color(42, 53, 66));
            btnFacturas.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));
        }else if(n == 5 ){
            btnSucursales.setBackground(new java.awt.Color(42, 53, 66));
            btnSucursales.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));
        }else if(n == 6 ){
            btnEmpleados.setBackground(new java.awt.Color(42, 53, 66));
            btnEmpleados.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));
        }else if(n == 7 ){
            btnPlanilla.setBackground(new java.awt.Color(42, 53, 66));
            btnPlanilla.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));
        }else if(n == 8 ){
            btnUsuarios.setBackground(new java.awt.Color(42, 53, 66));
            btnUsuarios.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));
        }
    }
    
    /**
     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Menu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aside;
    public javax.swing.JPanel body;
    public javax.swing.JLabel btnDashboard;
    private javax.swing.JLabel btnEmpleados;
    private javax.swing.JLabel btnFacturas;
    private javax.swing.JLabel btnPlanilla;
    private javax.swing.JLabel btnProductos;
    private javax.swing.JLabel btnProveedores;
    private javax.swing.JLabel btnSucursales;
    public javax.swing.JLabel btnUsuarios;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
