
package vistas.modulos;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.StandardChartTheme;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.StandardBarPainter;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.ui.RectangleInsets;

public class Dashboard extends javax.swing.JPanel {

    
    public Dashboard() {
        initComponents();
        getBarChart();
    }
    
    public void getBarChart(){
        
        String fontName = "Segoe UI";
            
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.addValue(30, "", "Enero");
        dataset.addValue(40, "", "Febrero");
        dataset.addValue(50, "", "Marzo");
        dataset.addValue(46, "", "Abril");
        dataset.addValue(80, "", "Mayo");
        dataset.addValue(40, "", "Junio");
        dataset.addValue(10, "", "Julio");
        dataset.addValue(67, "", "Agosto");
        dataset.addValue(50, "", "Septiembre");
        dataset.addValue(60, "", "Octubre");
        dataset.addValue(100, "", "Noviembre");
        dataset.addValue(90, "", "Diciembre");
        
        
        //JFreeChart jchart = ChartFactory.createBarChart("Cantidad de Ventas Realizadas por Mes", "Meses", "Cantidad", dataset, PlotOrientation.VERTICAL, true, true, false);
        JFreeChart jchart = ChartFactory.createBarChart("Cantidad de Ventas realizadas por Mes", "Meses", "Cantidad", dataset, PlotOrientation.VERTICAL, false, true, false);

        
        StandardChartTheme theme = (StandardChartTheme)org.jfree.chart.StandardChartTheme.createJFreeTheme();
        theme.setTitlePaint(Color.decode("#333333"));
        theme.setExtraLargeFont(new Font(fontName,Font.BOLD, 15)); //title
        theme.setLargeFont(new Font(fontName,Font.BOLD, 15)); //axis-title
        theme.setRegularFont(new Font(fontName,Font.PLAIN, 11));
        theme.setRangeGridlinePaint(Color.decode("#e6e6e6"));
        theme.setPlotBackgroundPaint(Color.white);
        theme.setChartBackgroundPaint(Color.white);
        theme.setGridBandPaint(Color.red);
        theme.setAxisOffset(new RectangleInsets(0,0,0,0));
        theme.setBarPainter(new StandardBarPainter());
        theme.setAxisLabelPaint(Color.decode("#666666"));
        theme.apply(jchart);
        
        jchart.getCategoryPlot().setOutlineVisible(false);
        jchart.getCategoryPlot().getRangeAxis().setAxisLineVisible(true);
        jchart.getCategoryPlot().getRangeAxis().setTickMarksVisible(false);
        jchart.getCategoryPlot().setRangeGridlineStroke( new BasicStroke() );
        jchart.getCategoryPlot().getRangeAxis().setTickLabelPaint( Color.decode("#666666") );
        jchart.getCategoryPlot().getDomainAxis().setTickLabelPaint( Color.decode("#666666") );
        jchart.setTextAntiAlias( true );
        jchart.setAntiAlias( true );
        jchart.getCategoryPlot().getRenderer().setSeriesPaint( 0, Color.decode( "#00A65A"));
        
   
        
        ChartPanel chartPanel = new ChartPanel(jchart);
        //barChart.removeAll();
        pChart.add(chartPanel);
        pChart.updateUI();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        header = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        article1 = new javax.swing.JPanel();
        totales = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        barChart = new javax.swing.JPanel();
        pChart = new javax.swing.JPanel();
        alertas = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        article2 = new javax.swing.JPanel();
        productos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaUltimasVentas1 = new rojerusan.RSTableMetro();
        ventas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaUltimasVentas = new rojerusan.RSTableMetro();
        jLabel2 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        header.setOpaque(false);
        header.setLayout(new java.awt.GridBagLayout());

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(42, 53, 66));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home_22px.png"))); // NOI18N
        jLabel3.setText("Dashboard / home");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        header.add(jLabel3, gridBagConstraints);

        add(header, java.awt.BorderLayout.PAGE_START);

        article1.setBackground(new java.awt.Color(255, 255, 255));
        article1.setOpaque(false);
        article1.setLayout(new javax.swing.BoxLayout(article1, javax.swing.BoxLayout.LINE_AXIS));

        totales.setBackground(new java.awt.Color(51, 122, 183));
        totales.setOpaque(false);
        totales.setLayout(new javax.swing.BoxLayout(totales, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel7.setBackground(new java.awt.Color(243, 156, 18));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/suitcase_60px.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel7.add(jLabel12, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Total de Empleados");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel7.add(jLabel13, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel7.add(jLabel14, gridBagConstraints);

        totales.add(jPanel7);

        jPanel9.setBackground(new java.awt.Color(0, 166, 90));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_group_60px.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel9.add(jLabel18, gridBagConstraints);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Total de Usuarios");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel9.add(jLabel19, gridBagConstraints);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel9.add(jLabel20, gridBagConstraints);

        totales.add(jPanel9);

        jPanel6.setBackground(new java.awt.Color(0, 192, 239));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/product_60px.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel6.add(jLabel9, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Total de Productos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel6.add(jLabel10, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel6.add(jLabel11, gridBagConstraints);

        totales.add(jPanel6);

        jPanel2.setBackground(new java.awt.Color(51, 122, 183));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/purchase_order_60px.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel2.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Total de Ventas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel2.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel2.add(jLabel8, gridBagConstraints);

        totales.add(jPanel2);

        article1.add(totales);

        barChart.setOpaque(false);
        barChart.setLayout(new java.awt.GridBagLayout());

        pChart.setBackground(new java.awt.Color(255, 255, 255));
        pChart.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 0, 0, 0, new java.awt.Color(51, 204, 0)));
        pChart.setLayout(new javax.swing.BoxLayout(pChart, javax.swing.BoxLayout.LINE_AXIS));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        barChart.add(pChart, gridBagConstraints);

        article1.add(barChart);

        alertas.setOpaque(false);
        alertas.setLayout(new java.awt.GridBagLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Alertas de Abastecimiento");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 0, 0, 0, new java.awt.Color(255, 102, 102)));
        jLabel5.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        alertas.add(jLabel5, gridBagConstraints);

        article1.add(alertas);

        add(article1, java.awt.BorderLayout.CENTER);

        article2.setBackground(new java.awt.Color(255, 255, 255));
        article2.setOpaque(false);
        article2.setLayout(new javax.swing.BoxLayout(article2, javax.swing.BoxLayout.LINE_AXIS));

        productos.setBackground(new java.awt.Color(255, 255, 255));
        productos.setOpaque(false);
        productos.setLayout(new java.awt.GridBagLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Últimos productos agregados");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 0, 0, 0, new java.awt.Color(204, 204, 204)));
        jLabel4.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        productos.add(jLabel4, gridBagConstraints);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jScrollPane3.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jScrollPane3.setOpaque(false);

        tablaUltimasVentas1.setBackground(new java.awt.Color(255, 255, 255));
        tablaUltimasVentas1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        tablaUltimasVentas1.setForeground(new java.awt.Color(255, 255, 255));
        tablaUltimasVentas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "Foto", "Descripción", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaUltimasVentas1.setAltoHead(30);
        tablaUltimasVentas1.setColorBackgoundHead(new java.awt.Color(249, 249, 249));
        tablaUltimasVentas1.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tablaUltimasVentas1.setColorBordeHead(new java.awt.Color(255, 255, 255));
        tablaUltimasVentas1.setColorFilasBackgound2(new java.awt.Color(249, 249, 249));
        tablaUltimasVentas1.setColorFilasForeground1(new java.awt.Color(51, 51, 51));
        tablaUltimasVentas1.setColorFilasForeground2(new java.awt.Color(51, 51, 51));
        tablaUltimasVentas1.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        tablaUltimasVentas1.setColorSelBackgound(new java.awt.Color(240, 240, 240));
        tablaUltimasVentas1.setColorSelForeground(new java.awt.Color(51, 51, 51));
        tablaUltimasVentas1.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        tablaUltimasVentas1.setFuenteFilas(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        tablaUltimasVentas1.setFuenteFilasSelect(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        tablaUltimasVentas1.setFuenteHead(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tablaUltimasVentas1.setGridColor(new java.awt.Color(255, 255, 255));
        tablaUltimasVentas1.setGrosorBordeFilas(0);
        tablaUltimasVentas1.setGrosorBordeHead(0);
        tablaUltimasVentas1.setMultipleSeleccion(false);
        tablaUltimasVentas1.setRowHeight(40);
        tablaUltimasVentas1.setRowSelectionAllowed(false);
        tablaUltimasVentas1.getTableHeader().setResizingAllowed(false);
        tablaUltimasVentas1.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tablaUltimasVentas1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        productos.add(jScrollPane3, gridBagConstraints);

        article2.add(productos);

        ventas.setOpaque(false);
        ventas.setLayout(new java.awt.GridBagLayout());

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jScrollPane2.setOpaque(false);

        tablaUltimasVentas.setBackground(new java.awt.Color(255, 255, 255));
        tablaUltimasVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        tablaUltimasVentas.setForeground(new java.awt.Color(255, 255, 255));
        tablaUltimasVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "Cliente", "Fecha", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaUltimasVentas.setAltoHead(30);
        tablaUltimasVentas.setColorBackgoundHead(new java.awt.Color(249, 249, 249));
        tablaUltimasVentas.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tablaUltimasVentas.setColorBordeHead(new java.awt.Color(255, 255, 255));
        tablaUltimasVentas.setColorFilasBackgound2(new java.awt.Color(249, 249, 249));
        tablaUltimasVentas.setColorFilasForeground1(new java.awt.Color(51, 51, 51));
        tablaUltimasVentas.setColorFilasForeground2(new java.awt.Color(51, 51, 51));
        tablaUltimasVentas.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        tablaUltimasVentas.setColorSelBackgound(new java.awt.Color(240, 240, 240));
        tablaUltimasVentas.setColorSelForeground(new java.awt.Color(51, 51, 51));
        tablaUltimasVentas.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        tablaUltimasVentas.setFuenteFilas(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        tablaUltimasVentas.setFuenteFilasSelect(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        tablaUltimasVentas.setFuenteHead(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tablaUltimasVentas.setGridColor(new java.awt.Color(255, 255, 255));
        tablaUltimasVentas.setGrosorBordeFilas(0);
        tablaUltimasVentas.setGrosorBordeHead(0);
        tablaUltimasVentas.setMultipleSeleccion(false);
        tablaUltimasVentas.setRowHeight(40);
        tablaUltimasVentas.setRowSelectionAllowed(false);
        tablaUltimasVentas.getTableHeader().setResizingAllowed(false);
        tablaUltimasVentas.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaUltimasVentas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        ventas.add(jScrollPane2, gridBagConstraints);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Últimas ventas realizadas");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 0, 0, 0, new java.awt.Color(102, 200, 239)));
        jLabel2.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        ventas.add(jLabel2, gridBagConstraints);

        article2.add(ventas);

        add(article2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel alertas;
    private javax.swing.JPanel article1;
    private javax.swing.JPanel article2;
    private javax.swing.JPanel barChart;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pChart;
    private javax.swing.JPanel productos;
    public rojerusan.RSTableMetro tablaUltimasVentas;
    public rojerusan.RSTableMetro tablaUltimasVentas1;
    private javax.swing.JPanel totales;
    private javax.swing.JPanel ventas;
    // End of variables declaration//GEN-END:variables
}
